name: build and release
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'
      - name: building
        id: building
        run: |
              chmod +x ./gradlew
              ./gradlew build
      - name: release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/libs/*.jar"
          name: Queue-Simulator
          tag: v1
